# Default values for app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  # Link to your container registry. You will launch it in Yandex Cloud.
  repository: cr.yandex/crp25c453ag6lhd6lhan/cdm_service
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v2024-06-11-r1"

containerPort: 5000

config:
  KAFKA_HOST: 'rc1a-56pampna4gtfqpph.mdb.yandexcloud.net'
  KAFKA_PORT: '9091'
  KAFKA_CONSUMER_USERNAME: 'producer_consumer'
  KAFKA_CONSUMER_PASSWORD: '123159357'
  KAFKA_CONSUMER_GROUP: 'consumer_group'
  KAFKA_SOURCE_TOPIC: 'dds-service-orders'

  PG_WAREHOUSE_HOST: 'rc1b-y16ysc19yf8dzygj.mdb.yandexcloud.net'
  PG_WAREHOUSE_PORT: '6432'
  PG_WAREHOUSE_DBNAME: 'sprint9dwh'
  PG_WAREHOUSE_USER: 'db_user'
  PG_WAREHOUSE_PASSWORD: 'postgres'

  REDIS_HOST: 'c-c9qsc5jc8jtaig3bb2i3.rw.mdb.yandexcloud.net'
  REDIS_PORT: '6380'
  REDIS_PASSWORD: 'Lfvbhrfcb,714' 

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
